# Generated by Django 4.2.5 on 2023-09-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserField',
            new_name='User',
        ),
    ]
