# Generated by Django 4.2.5 on 2023-09-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_userfield_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
