# Generated by Django 4.2.5 on 2023-09-13 09:40

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=api.utils.generate_id, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
